name: Deploy Frontend to Azure Static Web Apps

trigger:
  branches:
    include:
      - Page-Init

jobs:
- job: BuildAndDeploy
  displayName: "Build and Deploy Frontend"
  pool:
    vmImage: ubuntu-latest

  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        cd Holocron.Web
        npm install
        npm run build
      displayName: 'Install dependencies and build frontend'

    # Step to retrieve Backend:BaseUrl from Azure App Configuration and create .env file
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureConnection-Holocron' 
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Retrieve Backend:BaseUrl from Azure App Configuration
          echo "Retrieving Backend:BaseUrl from Azure App Configuration..."
          BACKEND_BASE_URL=$(az appconfig kv show --name holocron-appconfig --key "Backend:BaseUrl" --query "value" -o tsv)

          # Check if we have a valid value for BACKEND_BASE_URL
          if [ -z "$BACKEND_BASE_URL" ]; then
            echo "Error: BACKEND_BASE_URL is empty"
            exit 1
          else
            echo "Successfully retrieved BACKEND_BASE_URL"
          fi

          # Create .env file and add the BACKEND_BASE_URL variable
          echo "Creating .env file with VITE_BACKEND_BASE_URL"
          echo "VITE_BACKEND_BASE_URL=$BACKEND_BASE_URL" > Holocron.Web/.env

          # Display the content of the .env file to ensure it was created correctly
          echo "Displaying contents of .env file:"
          cat Holocron.Web/.env
      displayName: 'Fetch Backend:BaseUrl from Azure App Configuration and create .env file'

    # Step to export environment variables from .env file for subsequent steps
    - script: |
        echo "Exporting environment variables from .env file"
        set -a
        source Holocron.Web/.env
        set +a
      displayName: 'Export environment variables from .env'

    - task: AzureStaticWebApp@0
      inputs:
        app_location: "Holocron.Web/dist"
        config_file_location: "Holocron.Web"
        azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
      displayName: 'Deploy to Azure Static Web Apps'

