name: Deploy Frontend to Azure Static Web Apps

jobs:
- job: BuildAndDeploy
  displayName: "Build and Deploy Frontend"
  pool:
    vmImage: ubuntu-latest

  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        cd Holocron.Web
        npm install
        npm run build
      displayName: 'Install dependencies and build frontend'

    - task: AzureStaticWebApp@0
      inputs:
        app_location: "Holocron.Web/dist"
        config_file_location: "Holocron.Web"
        azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
      displayName: 'Deploy to Azure Static Web Apps'