# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: 'AzureConnection-Holocron'
  webAppName: 'lsanwebapp01'
  resourceGroupName: 'Tu-Resource-Group'
  environmentName: 'Development'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet build --configuration Release
  displayName: 'Build Backend'

- script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)/backend
  displayName: 'Publish Backend'

- task: AzureWebApp@1
  inputs:
    azureSubscription: $(azureSubscription)
    appName: $(webAppName)
    appType: webApp
    package: '$(Build.ArtifactStagingDirectory)/backend'
    resourceGroupName: $(resourceGroupName)
    appSettings: |
      ConnectionStrings__DefaultConnection=$(SQL_CONNECTION_STRING)
