name: Deploy Frontend to Azure Static Web Apps

trigger:
  branches:
    include:
      - Page-Init

jobs:
- job: BuildAndDeploy
  displayName: "Build and Deploy Frontend"
  pool:
    vmImage: ubuntu-latest

  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureConnection-Holocron' 
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Retrieving Backend:BaseUrl from Azure App Configuration..."
          BACKEND_BASE_URL=$(az appconfig kv show --name holocron-appconfig --key "Backend:BaseUrl" --query "value" -o tsv | tr -d '"')

          if [ -z "$BACKEND_BASE_URL" ]; then
            echo "Error: BACKEND_BASE_URL is empty"
            exit 1
          else
            echo "Successfully retrieved BACKEND_BASE_URL"
          fi

          echo "Setting the VITE_BACKEND_BASE_URL variable"
          echo "##vso[task.setvariable variable=VITE_BACKEND_BASE_URL]$BACKEND_BASE_URL"
      displayName: 'Fetch Backend:BaseUrl from Azure App Configuration'

    - script: |
        cd Holocron.Web
        echo "Using VITE_BACKEND_BASE_URL: $(VITE_BACKEND_BASE_URL)"
        npm install
        npm run build
      displayName: 'Install dependencies and build frontend'

    - task: AzureStaticWebApp@0
      inputs:
        app_location: "Holocron.Web/dist"
        config_file_location: "Holocron.Web"
        azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
      displayName: 'Deploy to Azure Static Web Apps'
