services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: HolocronDb
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourPassword123"
      ACCEPT_EULA: "Y"
    networks:
      - holocron-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Holocron.Api/Dockerfile
    container_name: holocron-api
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=HolocronDb;User Id=sa;Password=YourPassword123;TrustServerCertificate=True;
    ports:
      - "5149:5149"
    networks:
      - holocron-network
    restart: unless-stopped

  frontend:
    build:
      context: ./Holocron.Web
      dockerfile: Dockerfile
    container_name: holocron-web
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5149
    networks:
      - holocron-network
    restart: unless-stopped

networks:
  holocron-network:
    driver: bridge
