trigger:
  branches:
    include:
      - main  # Ajusta el nombre de la rama si es necesario

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '18'  # Ajusta según la versión de Node.js en tu App Service
  AZURE_WEBAPP_NAME: 'holocron-web-app'  # Nombre del App Service en Azure
  AZURE_SUBSCRIPTION: 'your-azure-subscription-id'  # ID de tu suscripción en Azure

steps:
  - task: UseNode@1
    inputs:
      version: $(NODE_VERSION)

  - script: |
      echo "Instalando dependencias..."
      npm install
    displayName: 'Instalar dependencias'

  - script: |
      echo "Construyendo la aplicación..."
      npm run build
    displayName: 'Compilar aplicación'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'dist'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    displayName: 'Empaquetar la aplicación'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
      artifactName: 'drop'
    displayName: 'Publicar artefacto'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'AzureConnection-Holocron'
      appName: 'lsanwebapp01'
      package: $(Build.ArtifactStagingDirectory)/app.zip
    displayName: 'Desplegar en Azure App Service'
